#include <iostream>
#include <QCoreApplication>
#include <QtBluetooth/qbluetoothlocaldevice.h>
#include "server.h"
#include <QBluetoothAddress>
#include <QtWidgets/qapplication.h>
#include <unistd.h>
#include <fstream>
#include <pthread.h>
#include <thread>
#include <signal.h>
#include <time.h>
#include <iomanip>
#include "shared_memory.h"
#include "concurrentbtle.h"
#include "singletonSM.h"
#include "powerController.h"
#include "pidcontroller.h"
#include "motor.h"
#include "cadenceblock.h"
#include "bcmencoder.h"