#define START_STOP           "a" // 
#define PID                   "b" // 
#define CURRENT_CADENCE       "c" // 
#define ANGLE_ENCODER         "d" // 
#define CHECK_STIM1           "e" // 
#define CHECK_STIM2           "f" // 
#define CHECK_PEDAL_LEFT      "g" // 
#define CHECK_PEDAL_RIGHT     "h" // 
#define CHECK_CARDIO          "i" // 
#define TRG_CAD               "j" // 
#define PID_PERCENTAGE        "k" // 
#define CURRENT_PERCENTAGE    "l" // 
#define QUAD_L                "m" // 
#define GLU_L                 "n" // 
#define HAM_L                 "o" // 
#define GAS_L                 "p" // 
#define QUAD_R                "q" // 
#define GLU_R                 "r" // 
#define HAM_R                 "s" // 
#define GAS_R                 "t" // 
#define HEART_RATE            "u" // 
#define CURRENT_OR_TARGET     "v" // 
#define ERROR                 "w" //
#define STIMULATOR_FREQUENCY  "x" //
#define STIMULATOR_PULSEWIDTH "y" //
#define LEFT_POWER            "z" //
#define RIGHT_POWER           "aa" //
